version: "3.7"

services:
  proxy:
    container_name: ${COMPOSE_PROJECT_NAME}-proxy
    image: ghcr.io/clayenapps/${COMPOSE_PROJECT_NAME}-proxy:latest
    build: proxy
    restart: unless-stopped
    ports: [ 80:80, 443:443 ]
    networks: [ public, internal ]
    cap_add: [ NET_ADMIN ]
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    env_file: [ "./proxy/.env" ]

  web:
    image: ghcr.io/clayenapps/office-web:latest
    container_name: ${COMPOSE_PROJECT_NAME}-web
    build: web
    restart: unless-stopped
    init: true
    expose: [ 3000 ]
    depends_on: [ api ]
    networks: [ public ]

  api:
    image: ghcr.io/clayenapps/office-api:latest
    container_name: ${COMPOSE_PROJECT_NAME}-api
    build: api
    restart: unless-stopped
    env_file: [ ./api/.env ]
    init: true
    expose: [ 3000 ]
    networks: [ public, internal ]

  db:
    image: postgres
    restart: unless-stopped
    expose: [ 5432 ]
    shm_size: 128mb
    env_file: [ ./api/.env ]
    volumes:
      - db:/var/lib/postgresql/data
    networks: [ internal ]

  adminer:
    image: adminer
    restart: "no"
    expose: [ 8080 ]
    depends_on: [ db ]
    profiles: [ adminer ]
    networks: [ internal ]

networks:
  public:
  internal:


volumes:
  db:
  caddy_data:
  caddy_config:
