version: "3.7"

services:
  proxy:
    container_name: ${COMPOSE_PROJECT_NAME}-proxy
    image: ghcr.io/clayenapps/${COMPOSE_PROJECT_NAME}-proxy:latest
    build: proxy
    restart: unless-stopped
    expose: [ 80 ]
    networks: [ public, internal ]
    cap_add:
      - NET_ADMIN
    volumes:
      - caddy_data:/data
      - caddy_config:/config

  web:
    image: ghcr.io/clayenapps/${COMPOSE_PROJECT_NAME}-web:latest
    build: web
    restart: unless-stopped
    init: true
    expose: [ 3000 ]
    depends_on: [ api ]
    networks: [ internal ]

  api:
    image: ghcr.io/clayenapps/${COMPOSE_PROJECT_NAME}-api:latest
    build: api
    restart: unless-stopped
    init: true
    expose: [ 3000 ]
    networks: [ internal ]

  db:
    image: postgres
    restart: unless-stopped
    expose: [ 5432 ]
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - db:/var/lib/postgresql/data
    networks: [ internal ]

  adminer:
    image: adminer
    restart: "no"
    expose: [ 8080 ]
    depends_on: [ db ]
    profiles: [ adminer ]
    networks: [ internal ]

networks:
  public:
  internal:


volumes:
  caddy_data:
  caddy_config:
  db:
