name: Build and deploy containers
permissions: write-all

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  web:
    name: Deploy web
    uses: './.github/workflows/docker-ghcr.yml'
    with:
      service: web

  api:
    name: Deploy api
    uses: './.github/workflows/docker-ghcr.yml'
    with:
      service: api

  notify:
    name: Send Telegram report
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [web, api]

    steps:
      - name: Send telegram message
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          disable_web_page_preview: true
          message: |
            Deployment workflow at [${{ github.repository }}](${{github.server_url}}/${{ github.repository }}) completed.

            Containers:
            - [web](https://ghcr.io/clayenapps/office-web): ${{ needs.web.result }}
            - [api](https://ghcr.io/clayenapps/office-api): ${{ needs.api.result }}
