name: Deploy project
permissions: write-all

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-push:
    name: ${{ matrix.image }}
    strategy:
      fail-fast: true
      matrix:
        image: [web, api]
    uses: ClayenApps/actions/.github/workflows/docker-ghcr.yml@main
    with:
      service: ${{ matrix.image }}

  deploy:
    name: Deploy
    needs: build-and-push
    uses: ClayenApps/actions/.github/workflows/portainer-redeploy.yml@main
    with:
      apiUrl: "https://admin.clayenkitten.ru/docker/api"
      serviceId: ${{ vars.PORTAINER_SERVICE_ID }}
      endpointId: ${{ vars.PORTAINER_ENDPOINT_ID }}
    secrets:
      token: ${{ secrets.PORTAINER_ACCESS_TOKEN }}

  notify:
    name: Send Telegram report
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [build-and-push, deploy]

    env:
      message: |
        *${{ github.repository }}*
        Project deployed successfully\\.

        *Status*
        Build: ${{ needs.build-and-push.result }}
        Deploy: ${{ needs.deploy.result }}
      repositoryBtn: |
        {
            "text": "Repository",
            "url": "${{github.server_url}}/${{ github.repository }}"
        }
      websiteBtn: |
        {
          "text": "Website",
          "url": "https://office.clayenkitten.ru"
        }
      workflowBtn: |
        {
          "text": "Workflow",
          "url": "${{github.server_url}}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        }

    steps:
      - name: Escape message
        id: escape
        run: echo "message=${message//$'\n'/\\n}" >> "$GITHUB_OUTPUT"

      - name: Send telegram message
        uses: fjogeleit/http-request-action@v1
        with:
          url: https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage
          method: "POST"
          data: |
            {
              "chat_id": "${{ secrets.TELEGRAM_TO }}",
              "text": "${{ steps.escape.outputs.message }}",
              "reply_markup": {
                  "inline_keyboard": [
                    [${{ env.repositoryBtn }}, ${{ env.workflowBtn }}],
                    [${{ env.websiteBtn }}]
                  ]
              },
              "parse_mode": "MarkdownV2",
              "link_preview_options": { "is_disabled": true }
            }
