name: Deploy project
permissions: write-all

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-push:
    name: ${{ matrix.image }}
    strategy:
      fail-fast: true
      matrix:
        image: [web, api]
    uses: ClayenApps/actions/.github/workflows/docker-ghcr.yml@main
    with:
      service: ${{ matrix.image }}

  deploy:
    name: Deploy
    needs: build-and-push
    uses: ClayenApps/actions/.github/workflows/portainer-redeploy.yml@main
    with:
      apiUrl: "https://admin.clayenkitten.ru/docker/api"
      serviceId: ${{ vars.PORTAINER_SERVICE_ID }}
      endpointId: ${{ vars.PORTAINER_ENDPOINT_ID }}
    secrets:
      token: ${{ secrets.PORTAINER_ACCESS_TOKEN }}

  notify:
    name: Send Telegram report
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [build-and-push, deploy]

    steps:
      - name: Send telegram message
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          disable_web_page_preview: true
          message: |
            **[${{ github.repository }}](${{github.server_url}}/${{ github.repository }})**

            Deploy workflow completed.

            Build: ${{ needs.build-and-push.result }}
            Deploy: ${{ needs.deploy.result }}

            See: https://office.clayenkitten.ru
