name: Deploy
permissions: write-all

on:
  workflow_call:
    inputs:
      build-context:
        required: true
        type: string
      service:
        required: true
        type: string
    secrets:
      GITHUB_TOKEN:
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Downcase repository name
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          echo "GITHUB_REPOSITORY=$(echo "$GITHUB_REPOSITORY" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.build-context }}
          push: true
          tags: ghcr.io/${{ env.GITHUB_REPOSITORY }}-${{ inputs.service }}:latest
